/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.function.Function;

import jooq.Keys;
import jooq.Public;
import jooq.tables.Company.CompanyPath;
import jooq.tables.Interactions.InteractionsPath;
import jooq.tables.records.ClientRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Client extends TableImpl<ClientRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.client</code>
     */
    public static final Client CLIENT = new Client();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClientRecord> getRecordType() {
        return ClientRecord.class;
    }

    /**
     * The column <code>public.client.client_id</code>.
     */
    public final TableField<ClientRecord, Long> CLIENT_ID = createField(DSL.name("client_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.client.full_name</code>.
     */
    public final TableField<ClientRecord, String> FULL_NAME = createField(DSL.name("full_name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.client.email</code>.
     */
    public final TableField<ClientRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.client.phone</code>.
     */
    public final TableField<ClientRecord, String> PHONE = createField(DSL.name("phone"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.client.company</code>.
     */
    public final TableField<ClientRecord, Long> COMPANY = createField(DSL.name("company"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.client.status</code>.
     */
    public final TableField<ClientRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.client.read_only_flag</code>.
     */
    public final TableField<ClientRecord, Boolean> READ_ONLY_FLAG = createField(DSL.name("read_only_flag"), SQLDataType.BOOLEAN.nullable(false), this, "");

    private Client(Name alias, Table<ClientRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Client(Name alias, Table<ClientRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.client</code> table reference
     */
    public Client(String alias) {
        this(DSL.name(alias), CLIENT);
    }

    /**
     * Create an aliased <code>public.client</code> table reference
     */
    public Client(Name alias) {
        this(alias, CLIENT);
    }

    /**
     * Create a <code>public.client</code> table reference
     */
    public Client() {
        this(DSL.name("client"), null);
    }

    public <O extends Record> Client(Table<O> path, ForeignKey<O, ClientRecord> childPath, InverseForeignKey<O, ClientRecord> parentPath) {
        super(path, childPath, parentPath, CLIENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ClientPath extends Client implements Path<ClientRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ClientPath(Table<O> path, ForeignKey<O, ClientRecord> childPath, InverseForeignKey<O, ClientRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ClientPath(Name alias, Table<ClientRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ClientPath as(String alias) {
            return new ClientPath(DSL.name(alias), this);
        }

        @Override
        public ClientPath as(Name alias) {
            return new ClientPath(alias, this);
        }

        @Override
        public ClientPath as(Table<?> alias) {
            return new ClientPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ClientRecord, Long> getIdentity() {
        return (Identity<ClientRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ClientRecord> getPrimaryKey() {
        return Keys.CLIENT_PKEY;
    }

    @Override
    public List<UniqueKey<ClientRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CLIENT_COMPANY_KEY, Keys.CLIENT_EMAIL_KEY);
    }

    @Override
    public List<ForeignKey<ClientRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CLIENT__CLIENT_COMPANY_FKEY);
    }

    private transient CompanyPath _company;

    /**
     * Get the implicit join path to the <code>public.company</code> table.
     */
    public CompanyPath company() {
        if (_company == null)
            _company = new CompanyPath(this, Keys.CLIENT__CLIENT_COMPANY_FKEY, null);

        return _company;
    }

    private transient InteractionsPath _interactions;

    /**
     * Get the implicit to-many join path to the
     * <code>public.interactions</code> table
     */
    public InteractionsPath interactions() {
        if (_interactions == null)
            _interactions = new InteractionsPath(this, null, Keys.INTERACTIONS__INTERACTIONS_CLIENT_ID_FKEY.getInverseKey());

        return _interactions;
    }

    @Override
    public Client as(String alias) {
        return new Client(DSL.name(alias), this);
    }

    @Override
    public Client as(Name alias) {
        return new Client(alias, this);
    }

    @Override
    public Client as(Table<?> alias) {
        return new Client(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Client rename(String name) {
        return new Client(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Client rename(Name name) {
        return new Client(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Client rename(Table<?> name) {
        return new Client(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Client where(Condition condition) {
        return new Client(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Client where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Client where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Client where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Client where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Client where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Client where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Client where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Client whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Client whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, String, String, Long, String, Boolean> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super Long, ? super String, ? super String, ? super String, ? super Long, ? super String, ? super Boolean, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super Long, ? super String, ? super String, ? super String, ? super Long, ? super String, ? super Boolean, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
