CREATE TABLE IF NOT EXISTS company(
    company_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL,
    discription TEXT
);

CREATE TABLE IF NOT EXISTS client(
    client_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL,
    company BIGINT UNIQUE REFERENCES company(company_id) ON DELETE CASCADE,
    status VARCHAR(100),
    read_only_flag BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS interactions(
    interactions_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT REFERENCES client(client_id) ON DELETE CASCADE,
    type_interactions VARCHAR(255) NOT NULL,
    date TIMESTAMP NOT NULL,
    notes TEXT
);

INSERT INTO company VALUES (1, 'ОАО Звездная', 'z@mail.ru', '8986545421', 'какой-то текст');
INSERT INTO company VALUES (1, 'ОАО Великая', 'S@mail.ru', '89865874566', 'какой-то текст');
INSERT INTO company VALUES (1, 'ОАО Русская', 'f@mail.ru', '8986548742', 'какой-то текст');
INSERT INTO client VALUES (1, 'Иванов Иван Иванович', 'I@mail.ru', '89874562145', 1, 'Новый', FALSE);
INSERT INTO interactions VALUES (1, 1, 'Инвестиции', '2023-05-15 14:30:00', 'какой-то текст');